# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node_registry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'node_registry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13node_registry.proto\x12\rnode_registry\"\x07\n\x05\x45mpty\">\n\x0fRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"\x18\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\t\"O\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\x12\x0e\n\x06status\x18\x05 \x01(\t\"1\n\x0cNodeResponse\x12!\n\x04node\x18\x01 \x01(\x0b\x32\x13.node_registry.Node\".\n\x08NodeList\x12\"\n\x05nodes\x18\x01 \x03(\x0b\x32\x13.node_registry.Node2\x8b\x02\n\x0cNodeRegistry\x12G\n\x08Register\x12\x1e.node_registry.RegisterRequest\x1a\x1b.node_registry.NodeResponse\x12\x35\n\x04List\x12\x14.node_registry.Empty\x1a\x17.node_registry.NodeList\x12=\n\x03Get\x12\x19.node_registry.GetRequest\x1a\x1b.node_registry.NodeResponse\x12<\n\x06\x44\x65lete\x12\x1c.node_registry.DeleteRequest\x1a\x14.node_registry.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_registry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=38
  _globals['_EMPTY']._serialized_end=45
  _globals['_REGISTERREQUEST']._serialized_start=47
  _globals['_REGISTERREQUEST']._serialized_end=109
  _globals['_GETREQUEST']._serialized_start=111
  _globals['_GETREQUEST']._serialized_end=135
  _globals['_DELETEREQUEST']._serialized_start=137
  _globals['_DELETEREQUEST']._serialized_end=164
  _globals['_NODE']._serialized_start=166
  _globals['_NODE']._serialized_end=245
  _globals['_NODERESPONSE']._serialized_start=247
  _globals['_NODERESPONSE']._serialized_end=296
  _globals['_NODELIST']._serialized_start=298
  _globals['_NODELIST']._serialized_end=344
  _globals['_NODEREGISTRY']._serialized_start=347
  _globals['_NODEREGISTRY']._serialized_end=614
# @@protoc_insertion_point(module_scope)
